package com.gradientgeeks.aegis.sfe_client.model

import com.google.gson.annotations.SerializedName

/**
 * Request model for signature validation with the Aegis Security API.
 * 
 * Used by backend services to verify the authenticity and integrity
 * of requests signed by client devices.
 */
data class SignatureValidationRequest(
    
    /**
     * Unique device identifier obtained during registration.
     * Used to identify which device's secret key should be used for validation.
     */
    @SerializedName("deviceId")
    val deviceId: String,
    
    /**
     * Base64-encoded HMAC-SHA256 signature to be validated.
     * Generated by the client device using its secret key.
     */
    @SerializedName("signature")
    val signature: String,
    
    /**
     * The exact string that was signed by the client device.
     * This typically includes HTTP method, URI, timestamp, nonce, and body hash.
     */
    @SerializedName("stringToSign")
    val stringToSign: String
)